export const SAVE_PRICE_TABLE_REQUEST = 'SAVE_PRICE_TABLE_REQUEST';
export const FETCH_PRICE_TABLE_REQUEST = 'FETCH_PRICE_TABLE_REQUEST';
export const UPDATE_PRICE_TABLE_REQUEST = 'UPDATE_PRICE_TABLE_REQUEST';
export const DELETE_PRICE_TABLE_REQUEST = 'DELETE_PRICE_TABLE_REQUEST';
export const PRICE_TABLE_SUCCESS = 'PRICE_TABLE_SUCCESS';
export const PRICE_TABLE_FAILURE = 'PRICE_TABLE_FAILURE';
export const FETCH_ALL_PRICE_TABLES_REQUEST = 'FETCH_ALL_PRICE_TABLES_REQUEST';
export const FETCH_ALL_PRICE_TABLES_SUCCESS = 'FETCH_ALL_PRICE_TABLES_SUCCESS';
