export const SAVE_LESSON_REQUEST = 'SAVE_LESSON_REQUEST';
export const FETCH_LESSON_REQUEST = 'FETCH_LESSON_REQUEST';
export const UPDATE_LESSON_REQUEST = 'UPDATE_LESSON_REQUEST';
export const DELETE_LESSON_REQUEST = 'DELETE_LESSON_REQUEST';
export const LESSON_SUCCESS = 'LESSON_SUCCESS';
export const LESSON_FAILURE = 'LESSON_FAILURE';
export const FETCH_ALL_LESSONS_REQUEST = 'FETCH_ALL_LESSONS_REQUEST';
export const FETCH_SEARCH_LESSONS_REQUEST = 'FETCH_SEARCH_LESSONS_REQUEST';
export const FETCH_ALL_STUDENT_LESSONS_REQUEST = 'FETCH_ALL_STUDENT_LESSONS_REQUEST';

