export const SAVE_STUDENT_REQUEST = 'SAVE_STUDENT_REQUEST';
export const FETCH_STUDENT_REQUEST = 'FETCH_STUDENT_REQUEST';
export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST';
export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST';
export const STUDENT_SUCCESS = 'STUDENT_SUCCESS';
export const STUDENT_FAILURE = 'STUDENT_FAILURE';
export const FETCH_ALL_STUDENTS_REQUEST = 'FETCH_ALL_STUDENTS_REQUEST';
export const FETCH_SEARCH_STUDENTS_REQUEST = 'FETCH_SEARCH_STUDENTS_REQUEST';
